[versions]
minecraft = "1.19"
yarn-mappings = "1.19+build.4"
fabric-loader = "0.14.8"

fabric-api = "0.58.0+1.19"

# Kotlin
kotlin = "1.7.10"
# Also modrinth version in gradle.properties
fabric-kotlin = "1.8.2+kotlin.1.7.10"

fabric-permissions = "0.1-SNAPSHOT"
translations = "1.4.16+1.19"

ktorm = "3.5.0"

konf = "1.1.2"

wdmcf = "1.0.2"

[libraries]
minecraft = { module = "net.minecraft:minecraft", version.ref = "minecraft" }
yarn-mappings = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

fabric-permissions = { module = "me.lucko:fabric-permissions-api", version.ref = "fabric-permissions" }
translations = { module = "fr.catcore:server-translations-api", version.ref = "translations" }

ktorm-core = { module = "org.ktorm:ktorm-core", version.ref = "ktorm" }
ktorm-sqlite = { module = "org.ktorm:ktorm-support-sqlite", version.ref = "ktorm" }

konf-core = { module = "com.uchuhimo:konf-core", version.ref = "konf"}
konf-toml = { module = "com.uchuhimo:konf-toml", version.ref = "konf"}

wdmcf = { module = "me.bymartrixx:wdmcf", version.ref = "wdmcf" }

